### PR TITLE
Re-working of bytecode transformers, fix for crashes in issue #1212

### PR DESCRIPTION
**Pull request by DoomFruit**
This is basically pull request #1283, but re-done to stop Github from getting confused with a load of un-necessary duplicate commits.

The changes are as follows:

-The Potion ID list can now safely be extended to 65535 if necessary. This required alterations to net.minecraft.potion.PotionEffect, net.minecraft.network.play.server.S1DPacketEntityEffect and net.minecraft.client.network.NetHandlerPlayClient. This affects save file compatibility between installations with AM2 (or DragonAPI) and vanilla, because active potion IDs were previously stored in an entity's NBT data as bytes - they're now integers.

-I have re-written all of the bytecode transformers to use the obf_deobf_pair helper subclass instead of having hard-coded search strings (where appropriate - some functions and signatures don't change between dev and live) - this means that everything will now work in a dev environment as well as in a live environment. It might also make it easier to update in the future.

-The bytecode transformer for EntityPlayerMP wasn't necessary and in fact, it wasn't even being called in the 1.7.10 version (it was still hard-coded for 1.6.4 function and variable names). I've commented it out, but left the (inactive) code there for future reference if necessary. As an interesting side note, it's quite fortuitous that this code never activated, since I imagine that it would have messed with the soulbound item fix.

-The bytecode transformer for NetServerHandler (which stopped you from being kicked for "invalid stance") was outdated, since the class name had changed. I've updated it to the newer NetHandlerPlayServer, along with changing a couple of GETFIELD to INVOKEVIRTUAL as necessary (new packet handling used wrapper functions to get these particular pieces of data out, rather than leaving them as public variables).

-The potion ID list is not extended if DragonAPI is installed. Both mods extend the potion list, and Bad Things happen when DragonAPI attempts to modify things if the relevant functions aren't vanilla. There should not be any problems if you remove DragonAPI from a modpack and let the potion ID extension code fall over to AM2, since the only persistent data is active potion effects on entities and in both mine and Reika's code, it's now stored as an integer instead of a byte. Removing both AM2 and DragonAPI (if present) will either cause all active potion effects to be removed or a flood of NPEs, depending on what Minecraft does. I don't see any way to avoid this.

-I've altered the LogHelper class so that it always displays AM2's debug messages (such as bytecode transformations) if you're in a dev environment. I am not massively happy with the way I did this, but I do not see any way of changing the logging level in code under Log4j 2.x (you could do it with 1.x, but they removed it for reasons which elude me). This basically means that the logging level is stuck at INFO and as such DEBUG messages do not show normally. This change is perhaps not directly relevant, but was vital for debugging and testing the bytecode transformers and so I left it in.

One thing I noted while testing is that the Ender Boots don't save their state if you log off and log on again. There were some lines commented out in ExtendedProperties.java which handle this. I uncommented them just to test (that change is not in this PR) and they seem to work fine, but that's not in the scope of this pull request, nor do I know whether this behaviour is intended (namely that if you step over the edge into open sky with the boots active, you'll never be able to play on that world again).

### CODE REVIEW

**Comment by Mithion** [comment]
The functionality of the Ender Boots saving was commented out before I added the height check.  Basically if you hit or surpass the build cap of the current world while under inverted gravity, it will turn them off preventing you from floating helplessly into space (though you could also just open your inventory and take them off, which would also stop the effect).  They probably should save, but like you said that isn't within the scope of this PR :)

Can you confirm that this works both client and serverside?

**Comment by DoomFruit** [comment]
I've tested this with a dedicated server and for whatever reason, the server doesn't seem to be sending the correct packets to the client (you get disconnected when casting a spell with an IndexOutOfBoundsException, indicating that the bytecode transformation didn't take).

Until I fix that and finish testing, do *not* fold this code into the main branch.

**Comment by DoomFruit** [comment]
Fixed it - missed out a semicolon on one of the signatures, so the code never found what it was looking for. Testing is still on-going for the other changes.

**Comment by DoomFruit** [comment]
Fixed it, missed out a single semicolon in one of the method descriptors. I also realised that I missed another packet (S1EPacketRemoveEntityEffect), which has been given a similar treatment to the S1D packet (though it was easier in this case, since its parameters were native integers). Testing is still on-going.

**Comment by DoomFruit** [comment]
I've tested the following in a dedicated server-client setup, all with no errors:
-Ender Boots (perspective flip, ceiling walking)
-Shrink Spell (activating and deactivating, checking first and third person perspective scaling)
-Potion IDs above 128, both starting and stopping.
-Scramble Synapses effect (caused by a creative mode spell, rather than fighting a lightning guardian)

Are there any more situations where the bytecode editing might come up with problems?

**Pull request merged**
