### PR TITLE
Mapping update

### PR DESCRIPTION
**Pull request by EoD**
This updates the mapping to "stable_12". As already mentioned in #1297, this deobfucates a lot of method names and fixes some wrong names (e.g. ``onGround``).

### CODE REVIEW

**Comment by EoD** [comment]
@Mithion Do you want me to keep rebasing those commits or would it be a waste of time as you are never going to merge it anyway?

**Comment by Mithion** [comment]
This commit won't be merged in to the next 1.7.10 update as it's beyond the scope of the update. 
I'm thinking that 1.8 should just be flat out skipped and we move straight to to 1.9.  

So, once 1.4.0.009 releases, I'm going to branch from master and create a 1.9 update...well, branch once Forge is ready to go.

This PR would make more sense to merge into the 1.9 update branch once it exists.

**Comment by EoD** [comment]
This PR is not more useful for a 1.8 (or even 1.9) branch than it is for a 1.7 branch. There will be plenty of (other) rework if you decide to go to 1.8.

**Comment by Mithion** [comment]
Quoting you, from #1297:
"This adds a lot of unknown methods/variables as well as updates the naming scheme to **make a potential update to 1.8 easier.**"

**Comment by EoD** [comment]
Yeah, the procedure I used to get from 1.7-default to 1.7-stable_12 can be reused in updating mappings to 1.8. The [result](https://github.com/EoD/mcp-tools/tree/master/mapping-updater) will be helpful for 1.8 update :)

**Comment by Mithion** [comment]
Fair enough, good to know it's at least reusable - anyways now I've outlined what I'm aiming for as far as version updates go, as well as the 1.7.10 update scope.  Hopefully that will help you tailor what you work on so that it isn't a wasted effort.

**Pull request closed without merging**
