### PR TITLE
Automatic allocation (kinda) for potion IDs, allows configuration of mana potion ID

### PR DESCRIPTION
**Pull request by DoomFruit**
While testing AM2 in my full modpack, I noticed that the mana potions seemed to have a hard-coded ID and could not be changed through the config file. This caused the game to not start when DragonAPI detected a potion clash with a debuff from RotaryCraft, threw an error to tell me what was going on and (rightfully) halted execution.

The cause was mana potions not being created the same way as other buffs - instead of using the createAMPotion() function which searches the config file for a potion ID, it just created a new potion directly using a hardcoded index. I've added a function to BuffList.java for mana potions which replicates the functionality of createAMPotion(), which means that the mana potions now have config file entries.

This is the main purpose of the pull request.

The secondary addition is as follows: While attempting to debug this (and not realising that it was a hard-coded variable issue), I also wrote some basic code for automatically finding the first available potion ID if no entry in the config file exists - this is in AMConfig.java. While it should be fully functional, bad luck means that it is far from perfect - in principle, this code should be well behaved and co-operative, but it's also loaded near the beginning (simply because the mod's name starts with A) and other mods may not be so nice with their own hard-coded potion ID values.

While it should theoretically be possible to change the potion allocations later in the startup procedure by making a table of what potions we allocate, and then checking that against what we end up with in post-initialisation (assuming that this is the final step before main menu), I don't know how "final" the potion list is after it's been created - some things might rely on the potion list after the allocation stage, for instance.

This also means that we're now bending over backwards to play nice with misbehaving mods who don't look at what they're stepping on. I have no idea what to do if this happens when we've already got a full config file (for instance - after adding a new mod to a complete installation, you might have buff or debuff effects active in your save which should not be arbitrarily re-assigned).

The automatic potion ID allocation in its current state is therefore functional, but not particularly useful unless you're adding AM2 to a modpack whose other contents start with AA to AL. I don't believe that it causes any harm, hence I've left it in the code for this pull request.

### CODE REVIEW

**Comment by Mithion** [comment]
One change I think would be beneficial is to check the potions array after retrieving the configured potion ID if it is different from the auto assigned one. If it's free, great, nothing needs to happen.  If there's already a potion there, you can then pop a message into the log indicating the potion conflict and the ID, as at that point we have a conflict.

This would help to locate issues with mods stepping on each other's toes when it comes to potion IDs and their seemingly constant conflicts.

You could also put a function call into postinit to ensure that all configured potion IDs are still in fact in their correct place/type in the potions array - not so much to auto-fix it (at least initially), but moreso to detect and identify when it happens rather than the wrong potion effect being applied mid-game, which is confusing to a player.

**Comment by DoomFruit** [comment]
Done and done. I've now got it seeing if the potion slot is already taken when trying to allocate a potion ID, keeping a log of what potions it assigns to where on startup and then checking in the postinit phase to see whether the allocations are still the same. When one of AM2's potions gets over-written, you get an entry like this in the log (the game will, however, still load):

[18:28:58] [Client thread/ERROR] [FML/arsmagica2]: Ars Magica 2 >> Error: my potion Epic Mana Restoration at index 35 has been over-written by another potion, wg.potionCinderCoat. You have a conflict in your configuration files.

**Comment by Mithion** [comment]
Excellent, thanks!

**Comment by chrisbecke** [comment]
My understanding of how potion ids are allocated (which is quite limited) is that it is not possible to have a client use server provided potion ids? The potion id sets MUST be manually synchronized between server and client via config?

Because all of this smart allocation of potion ids would seem to make things more sensitive to mod load order differences between the client and server (say, if a server has disabled some mods in a common mod pack or if OS differences simply cause mods to enumerate in a different order).

**Comment by DoomFruit** [comment]
Potion IDs are only generated if you don't have one set up in the config file. If you're playing on a server, you're going to need synchronised config files anyway, so I don't see this being an issue.

**Comment by chrisbecke** [comment]
I mostly agree. However, a lot of servers run premade modpacks to avoid having to distribute their own modpack and/or config. "Download FTB Infinity and connect". kind of thing. Then, players request a mod not present in the pack. Say, Ars Magica :) Which is easy for the server ops to add, and easy to tell the players to download.
The wrinkle is, if the mod being added, then needs custom config to be compatible with the pack.
So, as it stands, if Ars Magica 2 is added to a modpack that includes, say, Witchery, there will (because of load order) be potion id conflicts.

**Comment by jjtParadox** [comment]
Blocks and items used to be the same way, where each one had to be manually allocated to an ID. Because of a limitation in Minecraft, potion effects need to be given an ID, which should be defined in a config file. 

Right now there is no good way of re-allocating a potion after starting Minecraft, which is why the potion ID cannot be sent from the server to the client.

If potion IDs go the way of block and item IDs, then can joining a server be (almost) seamless.

**Comment by chrisbecke** [comment]
Yes.
Well - until that comes to pass - you could implement something where the potion id code could be configured to write out new, non conflicting id's, at runtime. They would not be used on the current run, but on a subsequent run they would (should) be unique.
An alternate configured mode would read the server values, write them to config and prompt the user to restart the client.
I just don't like the way this auto-reassignment would play out in more pathalogical situations where other mods are also adjusting their ids, or the user is playing against multiple different servers with different ids, and then tries to play their singleplayer game where they or mobs has an existing potion effect with a now-invalid id.

**Comment by DoomFruit** [comment]
Seeing as how every single mod in the game will have this problem with changing potion (and enchantment) IDs on different servers, I'm not particularly worried. And potion IDs will not be automatically generated if you've already got an entry in the AM2 config file. The auto-assignment code is only useful for the initial setup.

And because of the reasons stated in your final point, I am definitely not going to put in code that changes the AM2 potions and enchantments to fit with a list supplied by a server. If you're playing on a modded server, you'll need that server's modpack anyway - which includes the config files. If you're playing on multiple servers, they will either have their own modpack with its own separate install or some of them might be using the same, standard modpack (eg. FTB Direwolf20).

**Pull request merged**
