### PR TITLE
Ru LANG

### PR DESCRIPTION
**Pull request by TheVizzy**

### CODE REVIEW

**Comment by TheVizzy** [comment]
Add only RU lang update! And fix!

**Comment by Adaptivity** [comment]
I'm against it. That's all.

**Comment by Mithion** [comment]
Why are you against it?

**Comment by Adaptivity** [comment]
It's breaks more things than fixes. I wont even check it, it's not worth it. This guy have no experience in mod translations.

**Comment by Adaptivity** [comment]
I suggest you to close it. You can check how many translations I've done by checking my Github commits. And this one is bad.

**Comment by Mithion** [comment]
Unfortunately I don't speak russian, so I can't verify myself.
Until any conflicts are resolved, I'm going to close this PR.

**Pull request closed without merging**
