### PR TITLE
Fix Tarma Root growth

### PR DESCRIPTION
**Pull request by EoD**
Currently, Tarma root can grow (naturally and via the growth spell component) on all stone and cobblestone blocks, no matter if it's dark or not.  This change fixes the behaviour and adjusts it such that it only grows in places with ``lightlevel < 4`` and respects the "EnumPlantType.Cave``, similar to the behaviour of mushrooms.

### CODE REVIEW

**Comment by Mithion** [comment]
I like the change to be more in line with common practices and APIs, but I want to remove the light level check - tarma root should have no such restrictions.

**Comment by EoD** [comment]
Then the description in the Compendium needs to be changed: https://github.com/Mithion/ArsMagica2/blob/master/src/main/resources/assets/arsmagica2/docs/ArcaneCompendium_en_US.xml#L2179

**Comment by Mithion** [comment]
You'd be correct there.  The compendium should be changed as well.  You can either add the change into this commit or I can do it on Monday when I am back at the computer with the repo set up.

**Comment by EoD** [comment]
As far as "the community" is concerned, changing the Compendium / allowing to grow Tarma Roots at  higher light levels is something people are not expecting from Ars Magica as of today:
https://www.reddit.com/r/feedthebeast/comments/2fu7e5/ars_magica_2_how_to_get_tarma_root/
http://imgur.com/NOt3l1S
https://www.reddit.com/r/feedthebeast/comments/23c4a4/ars_magica_farming/

I just want you to be aware of this, if you change it.

**Comment by Mithion** [comment]
That's what changelogs are for :)
Tarma root was only ever supposed to grow on stone anyways.

**Comment by EoD** [comment]
A balancing perspective from our server:
Currently the Tarma Root is the most rare resource there (even more Rare than diamonds) and growing it via a spell everywhere (not only caves/dark places) makes it extremely easy to obtain. This means, once you got the Growth Spell, you get an extremely rare resource very very easily.

 I could change the percentages to obtain an AM2 flower by the "Grow" component even more in order to keep the balance while allowing Tarmas to be grown during sunlight.

**Comment by Mithion** [comment]
If it's a balance issue and commonly requested, I'm ok with having it only grow in dark places still.  I've just had a lot of complaints that it's *too* hard to obtain.  I suppose we could make the light requirement configurable, but the stone growing is a must.

However, in any case I don't want it to pop off if lit like mushrooms do.  That's just annoying.

**Comment by EoD** [comment]
Stone requirement: The stone requirement is not set inside ``canBlockStay`` as far as I know.

Light level: I can have a look if the root really pops off if it is lit up, but I would be surprised.

About spawning Tarma Roots: Currently, nothing keeps it from growing in not-so-dark places, but they are not spawned by the world gen, so my change does not make them more rare than they currently are.

**Comment by Mithion** [comment]
I believe you're right - canBlockStay is the light level checks and such.  
canPlaceBlockOn should be able to handle stone placement.

I'm not sure either off the top of my head if they pop off in light currently, but I just wanted to make sure that they don't.

Incorrect.  They do spawn via worldgen.  I direct your attention to line 104 on https://github.com/Mithion/ArsMagica2/blob/master/src/main/java/am2/worldgen/AM2WorldDecorator.java

I agree completely that they're too rare - some balance tweaking to the spawn weight is definitely in order.

**Comment by EoD** [comment]
I will not touch ``canPlaceBlockOn``

The plants do indeed pop off if the light level is too high (not instantly, but after a while). Could we still agree on a light level <= 12? This is the same as for mushrooms and only happens very close to torches or in direct sunlight ( http://minecraft.gamepedia.com/Light#Other ).

I checked AM2WorldDecorator.java#L104 a while ago and I dug through the code, but I could find nothing which explains that it so much more rare than desert novas for instance. Hence I guessed that it was related to ``EnumPlantType``.

**Comment by Mithion** [comment]
Tarma root grows on stone and shouldn't break due to light.
If that's out of the scope of what you want to fix in this issue, feel free to close it.

**Comment by EoD** [comment]
My change does not change the behaviour of Tarma's growing on Stone. 

My goal was to disable Tarma's from growing with the Grow component in other places than they are being spawned in naturally. That's why I went for the light level comparison (i.e. compendium's "in dark places").

If you have a better idea on how to make the Grow component behave more like the spawning algorithm, feel free to share your thoughts.

**Comment by Mithion** [comment]
Alright, so I've taken some time and given this some more thought; I'd rather the light level not affect whether the tarma root can stay - the initial growing should be done in the dark, but once grown it should stay no matter what.

The reasons behind this, are that the compendium should be followed in that it grows in dark places, but with the rarity that it tends to have, causing light to destroy it would only multiply that problem.

So if you can remove that, I will merge in the rest of the PR.

**Comment by EoD** [comment]
I like the idea. Just to be sure that we are talking about the same thing:
* Tarma roots should only spawn only in "dark places"
* Tarma roots should only grow by the Grow component in "dark places"
* Tarma roots will stay in sunlight if placed in sunlight (i.e., ``canBlockStay()`` will not reference to any light value)

**Comment by Mithion** [comment]
Yes, you got it - we're on the same page.

**Comment by EoD** [comment]
I rewrote the PR.

Additionally to our points above, I also increased the spawning height from 126 to 255 (to be consistent with vanilla flower spawning). I hope you don't mind?

**Comment by Mithion** [comment]
255 is fine there, yeah.  If there happen to be caves that high might as well have the roots able to grow there.

**Pull request merged**
