### PR TITLE
Fix projectile spells

### PR DESCRIPTION
**Pull request by jjtcomkid**
Looks like some debug stuff was left with some extra WIP homing projectile code, causing projectiles to not travel in any recognizable path. This should fix projectiles, and the homing code can be completed later.

### CODE REVIEW

**Comment by jjtcomkid** [comment]
Any update on this request?

**Comment by Mithion** [comment]
Don't really see the point to this one - I'd rather just fix homing projectiles than disable them.

**Comment by jjtcomkid** [comment]
Ok! Are all projectiles supposed to be homing?

**Comment by Mithion** [comment]
It's a modifier I was working on adding.  The flag should be set on projectile creation (Shapes/Projectile.java) based on whether or not the modifier is present in the spell.

**Comment by jjtcomkid** [comment]
Just added homing functionality and the code for the homing projectile modifier

**Comment by Mithion** [comment]
Nice!  Looks like I was in the right ballpark, I just couldn't seem to get the math to work out right to actually make it follow properly.

Out of sheer curiosity: is there any reason you used a modifier count rather than a modifier present check?  I'm curious as to what the effect of adding multiple homing modifiers would be.

If there isn't a reason (ie one modifier per spell is all you need), it may be better to use a check along the lines of ModifierIsPresent, which is marginally faster in most cases.  Since many NPCs and players use projectiles, that speed increase could add up.

**Comment by DoomFruit** [comment]
One possible reason I could think of multiple homing modifiers is to change the way in which the projectile homes - lag-pursuit (projectile aims at the target's current location - it will be constantly turning as it flies unless the target is heading towards or away from the projectile) for 1 modifier vs. lead-pursuit (projectile aims at where the target is expected to be, factoring in the projectile speed and target velocity - it will only change direction if the target changes speed or direction) for 2 modifiers.

**Comment by jjtcomkid** [comment]
Another alternative could be multiple homing modifiers increases the turn rate or homing detection radius of the projectile.

My two cents with lead-persuit is that most minecraft entities move in bursts of speed, never continually moving. If more entities were always moving, maybe then lead-persuit could be an option.

As for the stackable modifier, I was basing the code off the other enumerated spell modifiers (didn't know at the time there was a check for if a modifier was present).

The math also may need to be improved, as the projectiles sometimes take a strange path when homing. I'll look into finding improvements.

**Comment by Mithion** [comment]
Works for me.  I generally keep things simple, and would go with a lag pursuit where the modifier changes detection radius/turn speed as jjtcomkid said.

**Pull request merged**
