### PR TITLE
Boss Animations

### PR DESCRIPTION
**Pull request by jjtParadox**
I noticed a long time ago that a lot of the boss animations seemed really choppy. After looking at the code, I figured out the animations were being timed against a tick, or running at 20 frames a second. Most of the code here fixes that, instead running the animations off the `f2` parameter from the `ModelBase.render()` method. 

I highly recommend doing a side by side comparison of an Ars Magica version before the animation smoothing and afterward, as the improved animations are most noticeable this way.

As I was fixing the timings of animations, I also added some idle movement to many of the bosses and fixed some modeling errors.

Another issue I quickly found was that some of the bounding boxes for some of the bosses were _tiny_, sometimes even less than half the boss. This caused both rendering quirks where a boss would stop rendering if you looked only at its upper half, as well as plenty of frustration over fighting certain bosses, where only body attacks would work as any attack aimed at the head would do nothing.

I've adjusted many of the boss bounding boxes, and so far the only downside I have noticed is that some bosses can't fit under ledges that they once might have been able to clip under. Boss spawning might need to be adjusted to account for a boss's extra size, so that no boss spawns with it's head stuck in a ceiling.

I also recommend the continued use of AnimationAPI, as all animations done with this API are extremely fluid and much easier to maintain.

As a side question, is the fire guardian supposed to heal from it's own firestorm? I can't determine if this is a bug or a feature.

### CODE REVIEW

**Comment by Mithion** [comment]
I specifically made the boss BBs that size so they could fit through hallways and doors.  This is an important aspect to fighting them. I believe there is (or at least was) a RenderBoundingBox property or method that should fix the render issues.

**Comment by jjtcomkid** [comment]
With the rendering issues, I believe there is a frustrum switch that would fix the rendering issues.

As for the fitting through doors, some of the bosses were set to a width of 1, which I believe would have not been able to fit through a door, since a door takes up a small amount of a block.

As for combat, I believe there may be a way to use entity parts (the actual class name is slipping my mind right now, the same parts the ender dragon uses) to have an upper half that is still targetable, while the lower half is the collision box.

**Comment by jjtcomkid** [comment]
I've figured out how to use `EntityDragonPart` to both let a boss travel through player sized spaces and to be hit in all areas.

However, there is a small bug with spell projectiles that causes them to ignore entity parts, which I have addressed in #1242.

Once this bug is fixed I can update this pull request with the new boss bounding boxes.

**Comment by Mithion** [comment]
#1242 has been merged in, have at it!

**Comment by jjtcomkid** [comment]
Tested with all the bosses and so far things look good!

The only case where I can imagine small bugs might occur is the player might need to be looking at the original bounds of the boss to interact or right-click it.

Otherwise, all damage against the boss works great!

**Pull request merged**
