### PR TITLE
1.8 Fixes

### PR DESCRIPTION
**Pull request by EdwinMindcraft**
Also Fixes Multiblock Structures Defs and the occulus
Adds More flexibility to SkillTrees

### CODE REVIEW

**Comment by williewillus** [comment]
When porting, I always try not to just straight up stick "new BlockPos" everywhere - try to refactor some of these methods to actually *take* BlockPos, which will not only look clearer, but will be easier to invoke and will have a lighter memory footprint

**Comment by williewillus** [comment]
Another thing - please please don't just stick getMetaFromState everywhere - truly attempt to port to blockstates, instead of inserting a hack back to the old system. For example, where you are switching over the ore meta, you should never switch over the int, you should be switching over an enum that enumerates the ore types. 

The concept is that NO ONE besides your getStateFromMeta/getMetaFromState should ever need to touch these ugly meta numbers.

This is not a breaking change, but it produces a much better codebase after you're finished porting.

**Comment by EdwinMindcraft** [comment]
To be fair I just fixed some of the basic blocks because I was seeing to much error in eclipse...

**Comment by EdwinMindcraft** [comment]
And I forgot blockstates

**Comment by williewillus** [comment]
As someone that has done several ports now, I really recommend against that. Changes need to be focused and comprehensive and complete. Don't start fixing something if you don't fix it all the way. I recommend fixing all method signatures first, then come back and do all blockstates together.

**Comment by EdwinMindcraft** [comment]
Hopefully finished blocks...

**Comment by williewillus** [comment]
He's already been working on blocks...

**Comment by Kolatra** [comment]
Currently am at this very moment.

**Comment by Kolatra** [comment]
Also looking through your branch, a lot of the blocks have been untouched still.

**Comment by williewillus** [comment]
There's a reason I like to solo ports ;p
Anyways, I'm still meh on this PR because it doesn't understand how blockstates work and overspams blockpos instead of refactoring to passing them around

**Comment by EdwinMindcraft** [comment]
Removed the new BlockPos everywhere in Multiblock structures defs

**Comment by Kolatra** [comment]
willie, it's not even a thing with soloing ports, there just has to be some coordination between those doing the work. Edwin, if you hopped onto IRC, we could easier coordinate and this port could be in a working state a lot quicker.

**Comment by EdwinMindcraft** [comment]
Looked through the Inlay Code... We might need another block to do progress...

**Comment by williewillus** [comment]
The blockstates look much better :D
There's still some spots where getStateFromMeta and getMetaFromState are called though which is a blockstate nono
Thanks for the contributions!

**Comment by EdwinMindcraft** [comment]
tiles getState and getMeta are placeholders,
If i missed in the blocks jest tell me :D

**Comment by Kolatra** [comment]
What I have decided for 1.8.9 PRs due to a few reasons is to not merge any of them, however I will include the changed code myself and give appropriate credit for code. Don't let this discourage you, you're doing great work.

**Comment by EdwinMindcraft** [comment]
So... Since the 1.8.9 Update seems to have died I'll close this PR. There's no need of keeping it.

**Pull request closed without merging**
