### PR TITLE
Code style cleanup and guidelines

### PR DESCRIPTION
**Pull request by jjtcomkid**
Suggested code style for issue #1226.

### CODE REVIEW

**Comment by Mithion** [comment]
Couple of changes I'd like to see in the template - it looks like it's rearranging method names to be alphabetic (or based on some other criteria) - if so, let's leave that out.  I prefer things to be grouped based on functionality, and would personally have trouble finding my way around if all the methods suddenly moved.  At further glance it may not be alphabetic, but I still don't prefer whatever it's doing there.

The other thing is that I'd like there to be no spaces in a cast - for example, 
((EntityFlicker)o).setDead();
should be as it is, not
((EntityFlicker) o).setDead();

Alphabetic imports are fine, as they are, I usually let the IDE add/remove them as necessary anyway.

Also just commenting on the "Fixed projectile spells" line so that it's here, that should be a different commit (as you already mentioned in #1226).

I don't see any other issues at first glance, will let you know.

**Comment by jjtcomkid** [comment]
Looks like I had the reformatter group entries by setter/getter pairs or by overwritten method class, then alphabetize. I'll fix that and also fix the extra commit.

**Comment by jjtcomkid** [comment]
Accidentally applied the formatter globally, fixing...

**Comment by Mithion** [comment]
Much better, thank you - I'm good with this style.  I'll update the readme.md over the weekend to reflect style guidelines moving forward.

**Pull request merged**
