### PR TITLE
Fix for crashes in issue #1212 (extended potion IDs)

### PR DESCRIPTION
**Pull request by DoomFruit**
After a fair bit of bashing on Mojang's code, I think I've managed to get around the array out of bounds exception noted in issue #1212 with potion IDs above 128. I've had to alter PotionEffect.java to change the way it saves active potion effects into your player character (was byte, now int), changed S1DPacketHandler.java to send integers instead of bytes, and had to additionally change NetHandlerClient to expect an integer instead of a byte from one of its function calls.

I've tested it in a pure AM2 dev environment, where a swift swim spell with potion ID 128 worked fine (previously, it failed by complaining about a clearly unphysical array index of -128). Testing it in my full modded setup revealed that whatever it is that DragonAPI does with respect to extending the potions array (which works fine with AM2 - I'm currently running a relatively early build of 009 on my server) clashes with my code, so I put in a check and don't do anything to potions if you have DragonAPI installed - there's no sense in duplicating effort, and Reika is almost certainly a better coder than I am.

I think it's solved the out of bounds potion ID issue, but could use another pair of eyes here.

### CODE REVIEW

**Comment by Mithion** [comment]
The transforms themselves look ok to me, however:

This style of ASM transforming isn't consistent with the rest of the file - using the obf_deobf_pair class will either need to be removed or the existing methods changed to use it as well.

**Comment by EoD** [comment]
@DoomFruit You might want to rebase your branch instead of "re-merge" the master branch. See [stackoverflow as an example](http://stackoverflow.com/questions/7297379/how-do-you-rebase-the-current-branchs-changes-on-top-of-changes-being-merged-in).

**Comment by DoomFruit** [comment]
In that case, I'll re-work the rest of the transformers. The reason I use the obf_deobf_pair is because the existing style doesn't do anything in a dev environment (the obfuscated names are hard-coded) and as such I wouldn't be able to test it out easily. Doing it this way makes it easier to handle version changes (the obfuscated and normal variable names are only mentioned once, and kept together) and ensures that it works in a deobfuscated environment as well.

And sure, I'll try the rebase approach. I know so very little about git and development in general - I do everything with a text editor, a command line and the web interface for Github,,,

**Comment by DoomFruit** [comment]
I've re-opened the pull request, but it's not ready yet. I've still got to fix 1 more function.

**Comment by jjtParadox** [comment]
What the-- for some reason GitHub is including 19 extra commits _that already exist_ with this pull request.

This really should not be happening...

You might just want to open a new pull request since for some reason comparing the branches https://github.com/Mithion/ArsMagica2/compare/master...DoomFruit:PotionIDExtensionFix works perfectly fine.

**Comment by DoomFruit** [comment]
I'm closing this pull request and will attempt to create a new one to try and get around the strange commit history.

**Comment by EoD** [comment]
@DoomFruit Just contact me via IRC and I will guide you through the commit issues.

**Comment by jjtParadox** [comment]
Just curious, what is causing this? I usually know my way around git but this is really messing with me.

**Comment by EoD** [comment]
Seems like some merging, rebasing and one too much force-push issue.

**Pull request closed without merging**
