### PR TITLE
Fixed chrono anchor dimension bug

### LINKED ISSUE #1289: Chrono anchor works strangely after crossing dimensions
If I cast chrono anchor, travel to another dimension, then wait for it to wear out, chrono anchor teleports me to the XYZ I was at when I cast chrono anchor, even when that original coordinate was in a different dimension.

In my test I was teleported above a pool of lava after I went from the overworld to the nether.

Should going across dimensions cancel the chrono anchor effect? Or should the chrono anchor effect go off when a player attempts to transfer to another dimension, canceling the transfer?

### PR DESCRIPTION
**Pull request by jjtParadox**
Fixed #1289 by removing the chrono anchor effect when an entity is spawned into a world (e.g. after it changes dimensions).

### CODE REVIEW

**Comment by Mithion** [comment]
This won't actually fix it, as it's only doing this on the client handler.  The problem will still exist on servers.

This fix should be proxied in the same way that dispel is; in that it removes the effect serverside and lets the server communicate that to the client.

**Comment by jjtParadox** [comment]
Whoops you're right about that. I had initially tested it in a SP world to make sure the integrated server wasn't tracking an anchor that the client didn't know about, and no bug came up. I'll move the event handler over to serverside.

**Comment by jjtParadox** [comment]
Fixed the handler and found a server crash bug in the process, so here's the updated fix!

**Comment by Mithion** [comment]
This PR includes other commits that it shouldn't - can you please remove the changes to:

src/main/java/am2/AMClientEventHandler.java 
* single import line, no point in importing it

src/main/java/am2/blocks/BlockAMOre.java
* this isn't related to this issue - I'd like to keep the commits clean and separate.  This should really be it's own commit

**Comment by jjtParadox** [comment]
Whoops yeah I forgot to clean up imports and didn't think to separate the changes, I'll fix that.

**Comment by jjtParadox** [comment]
Sorry for the delay, life's been busy lately.
Separated out the commits and cleaned up the imports!

**Pull request merged**
