### PR TITLE
Rewrite grow spell component

### PR DESCRIPTION
**Pull request by EoD**
I rewrote the whole Grow component to allow growing of non-vanilla flowers and plants. Additionally I nerfed the spell a lot, such that you need more than one attempt to grow a flower.

I also removed the particle effect on a hit if the target can't grow anything. This way you know if you should hit it more often to grow something or if you should move on.

I will remove the farmland commit once the discussion in #1291 has come to the conclusion.

### CODE REVIEW

**Comment by Mithion** [comment]
Couple of notes.  First few are likely related to you playing around with balancing as you tested.  The other is relating to mana cost.

Not sure how to reference lines directly, but on lines 52/53 you mention in a comment that it is a 6% grow chance but the math works out to 4% - these should be brought in line.

On lines 109/116 you mention a 60% chance of growing but the math works out to 40%.  Again, this should be brought into line. 

There's other instances of this on line 98/102, 88/91, 78/81.

Returning "false" to not spawn particles will also negate the mana cost of this component if nothing is grown.  I'd like to discuss the implications of this and determine if it is in fact a good idea to do so.

**Comment by EoD** [comment]
Oh indeed, I thought the range form NextInt(x) is from ``1 to x``, not ``0 to x-1``. I will correct this. The numbers in the commentary section are twice the numbers of the code as for some reason (which I could not figure out) the code is executed twice when the spell hits a block. Maybe you have an idea?

About returning "false", I did not know that I also remove the mana cost. What are you preferences regarding that matter?

**Comment by EoD** [comment]
@Mithion Can we merged the first bits? I am happy to remove the latest commit and rewrite it once we concluded #1291 if that's what you prefer.

**Comment by Mithion** [comment]
Let's just figure it all out first and then merge it in.

**Comment by Mithion** [comment]
To answer your previous question, my style is that mana should be deducted if the spell is even attempted to be applied on a block.  Generally the only time false is returned is if there is some sort of glitch or other occurrence that prevents the attempt from even happening.  In this case, the spell is attempting to apply to the block successfully, it just isn't finding a valid target.

So I would return true here and deduct the mana.

**Comment by EoD** [comment]
>Let's just figure it all out first and then merge it in.

That's why I wanted to remove the last commit and put it into another PR/branch. As far as I understood you, this is the only one in question here.

>So I would return true here and deduct the mana.

I will let it return true.

**Comment by EoD** [comment]
As #1291 is finished, we can merge this PR?

**Comment by Mithion** [comment]
The component isn't executed twice - so I'd still like to see the comments corrected to the actual intended percentage chances.  Unless I'm missing something and it is in fact executed twice?

The code itself looks good to me, so as soon as we're clear on the comments I'll merge it in.

**Comment by EoD** [comment]
The problem was that my log showed both logs of the client and the server, so I got the log message that the grow component has been executed twice (once from the client, once from the server). I didn't expect this to happen.

**Pull request merged**
